#!/bin/bash -ex
source $(dirname $0)/functions

# Rename the host
HOSTNAME=rails
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts

# Use mirrors.163.com as the default apt repository
rm -f /etc/apt/sources.list.d/*.list
apt-get update

# Enable locale zh_CN.UTF-8
/usr/share/locales/install-language-pack zh_CN.UTF-8
echo 'LANG=zh_CN.UTF-8' > /etc/default/locale
echo 'LC_ALL=zh_CN.UTF-8' >> /etc/default/locale

# Install ruby-1.9.2 and set it as default
install build-essential bison openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev
/usr/local/rvm/bin/rvm install 1.9.2
/usr/local/rvm/bin/rvm use 1.9.2 --default

# Install passenger and nginx
install libcurl4-openssl-dev
/usr/bin/env /usr/local/rvm/bin/ruby -S gem install passenger --no-ri --no-rdoc
/usr/bin/env /usr/local/rvm/bin/ruby -S passenger-install-nginx-module --auto --auto-download --prefix=/usr/local/nginx
